### ISSUE TITLE
Script hosting

### ISSUE THREAD

**Issue by gitsheikhgit** [Jitendraunatti/youtube#1]
You said
 “THIS LINK IS FUNCTIONAL UNTIL CLOUDFLARE DON'T INCUR ANY CHARGES FROM ME.”
Can I host this script on a VM locally to not have limit like cloudflare?

**Comment by Jitendraunatti** [comment]
Yes, you can, but I have not yet released its code.

**Comment by gitsheikhgit** [comment]
Ok I’ll be waiting for you to make it available
