### ISSUE TITLE
some live channels not working

### ISSUE THREAD

**Issue by DheerCodes** [Jitendraunatti/youtube#2]
Hello bhai,
I am trying to play this script for some kids channels but its not working.
e.g
https://www.youtube.com/watch?v=2UOwO_N17ms
https://youtube.jitendraunatti.workers.dev/wanda.m3u8?id=2UOwO_N17ms

https://www.youtube.com/watch?v=IJbbpAhjboI
https://youtube.jitendraunatti.workers.dev/wanda.m3u8?id=IJbbpAhjboI

**Comment by Jitendraunatti** [comment]
Everything is working from my end; use the backup link for a better experience

**Comment by Jitendraunatti** [comment]
![image](https://github.com/user-attachments/assets/0d3b4407-e1cd-4d98-ae15-2e1372d35abb)

**Comment by DheerCodes** [comment]
Not working for me, I am trying with VLC, browser and IPTV player apps.
I am trying this from India
Sometimes its plays dummy video as attached 


![Youtube-2-m3u8 error](https://github.com/user-attachments/assets/7abd1878-25fa-469b-8f21-e80a2824583e)

**Comment by DheerCodes** [comment]
Just tried with US vpn and it's working 
How can I play this in India without VPN 

![Screenshot_2024-12-04-20-33-47-64_013dba30cae4674f6b0947ea3c272499](https://github.com/user-attachments/assets/71b3fd38-5848-44ef-af93-eedf019f547f)

**Comment by Jitendraunatti** [comment]
![image](https://github.com/user-attachments/assets/878fc59d-abba-467e-a693-caaa2694ddce)
I don't know what the issue is on your end, but it works for me on VLC Media Player when I'm in India

**Comment by DheerCodes** [comment]
yes bro, really don't know the issue, not working for me.
will it possible to host this script somewhere in India, or if you can share it.
